language: php

php:
  - 5.6
  - 7.1
  - 7.2
  - 7.3

before_script:
  - composer install

script:
  - composer test
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" ]; then php ./vendor/bin/phpdoc; fi'

branches:
  only:
    - master
    - develop

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: pages
  local_dir: documentation/complete
  cleanup: false
  token: $GITHUB_TOKEN
  on:
    branch: master
